# Generated by Django 5.2.6 on 2025-10-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartTrav', '0003_destination_category_destination_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='category',
            field=models.CharField(choices=[('resort', 'Resort'), ('restaurant', 'Restaurant'), ('attraction', 'Attraction'), ('beach', 'Beach'), ('historical', 'Historical Site')], max_length=100),
        ),
        migrations.AlterField(
            model_name='destination',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
