# Generated by Django 5.2.6 on 2025-10-04 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartTrav', '0004_alter_destination_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartTrav.destination')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartTrav.itinerary')),
            ],
            options={
                'ordering': ['added_at'],
                'unique_together': {('itinerary', 'destination')},
            },
        ),
    ]
