# Generated by Django 5.2.6 on 2025-11-26 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartTrav', '0005_itinerarydestination'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='itinerarydestination',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_destinations', to='SmartTrav.itinerary'),
        ),
    ]
