# Generated by Django 5.2.6 on 2025-12-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartTrav', '0006_destination_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='images/'),
        ),
    ]
