# Generated by Django 5.2.6 on 2025-12-02 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartTrav', '0007_alter_destination_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='image',
        ),
    ]
