# Generated by Django 5.2.6 on 2025-12-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartTrav', '0009_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerarydestination',
            options={'ordering': ['visit_date', 'visit_time', 'added_at']},
        ),
        migrations.AddField(
            model_name='itinerarydestination',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itinerarydestination',
            name='visit_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
