# Generated by Django 5.2.6 on 2025-12-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartTrav', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=1500.0, help_text='Cost per day in PHP', max_digits=10),
        ),
        migrations.AddField(
            model_name='destination',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags (e.g., beach, family, budget)', max_length=500),
        ),
        migrations.AddField(
            model_name='itinerarydestination',
            name='calculated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
