# Generated by Django 5.2.6 on 2025-12-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartTrav', '0010_destination_price_per_day_destination_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=2500.0, help_text='Cost per day in PHP (1000-5000)', max_digits=10),
        ),
    ]
